# App
name = "ImNimble"
comment = "ImNimble is a simple Dear ImGui application example"
version = "0.4.0"
website = "https://github.com/Patitotective/ImNimble"
authors = ["Patitotective <https://github.com/Patitotective>"]
categories = ["Utility"]

# AppImage
ghRepo = "Patitotective/ImNimble"

stylePath = "assets/style.toml"
iconPath = "assets/icon.png"
svgIconPath = "assets/icon.svg"
iconFontPath = "assets/forkawesome-webfont.ttf"
fontPath = "assets/Karla-Regular.ttf"
strongFontPath = "assets/Karla-Bold.ttf"
monoFontPath = "assets/UbuntuMono-Regular.ttf" #"assets/ProggyVector Regular.ttf"
fontSize = 16.0

# Window
minSize = [600, 400] # Width, height

# Settings for the preferences window
[settings.nimbleCmd]
display = "Nimble command"
type = "input"
default = "nimble"
max = 100
flags = "None" # See https://nimgl.dev/docs/imgui.html#ImGuiInputTextFlags
help = "Command to call Nimble with"
[settings.autoScroll]
display = "Auto scroll"
type = "check"
default = true
help = "Scroll to bottom whenever a command is added to the console"
